services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: neuroglancer-plugin-backend
    ports:
      - '8001:8000'
      - '8002:8002'
    volumes:
      - ouroboros-volume:/volume
    extra_hosts:
    - "host.docker.internal:host-gateway"

volumes:
  ouroboros-volume:
    external: true
    name: ouroboros-volume
